
# flux Helmchart to grab the nginx ingress controller chart
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: nginx
spec:
  chart: nginx/nginx-ingress-controller
  version: 1.7.0
  interval: 5h # How often to reconcile the HelmChart
  sourceRef:
    kind: HelmRepository
    name: nginx
