
# flux Helmchart to grab the nginx ingress controller chart
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 2.2.x # Specify the version of the chart to use
  interval: 5h # How often to reconcile the HelmChart
  sourceRef:
    kind: HelmRepository
    name: nginx
