
# flux HelmRelease for installing Nginx Ingress Controller for helm chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: 2.2.x # Specify the version of the chart to use
      interval: 5h # How often to reconcile the HelmRelease - check for new chart
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: nginx
  interval: 1h # This is for drifting of the helm created resources


