

# flux HelmRepository for installing Nginx Ingress Controller
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  url: oci://ghcr.io/nginx/charts
  type: oci